---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
    labels:
      - "ci-skippush"
  - package-ecosystem: "docker"
    directories: 
      - "/apps/whoami"
      - "/images/gha-runner"
    schedule:
      interval: "daily"
    labels:
      - "ci-skippush"
