name: RELEASE

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  INIT:
    uses: ./.github/workflows/rw-init.yaml

  CI:
    needs: INIT
    uses: ./.github/workflows/rw-ci.yaml
    with:
      paths_modified: ${{ needs.INIT.outputs.paths_modified }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  CD:
    needs: [INIT, CI]
    uses: ./.github/workflows/rw-cd.yaml
    with:
      paths_modified: ${{ needs.INIT.outputs.paths_modified }}
      tags: ${{ needs.CI.outputs.tags }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}