name: CD

on:
  workflow_call:
    inputs:
      paths_modified:
        type: string
        description: List of modified apps
      skip_cd:
        type: string
        description: Apps to skip continuous deployment
        default: gha-runner
        required: false
      tags:
        type: string
        description: Docker image tags
        required: true
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
        
jobs:
  CD:
    runs-on: self-hosted
    strategy:
      matrix:
        apps: ${{ fromJson(inputs.paths_modified) }}
    steps:
    - name: Git clone the repository
      uses: actions/checkout@v4

    - name: Set up Helm
      uses: azure/setup-helm@v4.2.0
      with:
        version: 'latest'

    - name: Deploy
      if: ${{ matrix.apps != inputs.skip_cd }}
      run: |
        sed -i "s/^name: .*/name: ${{ matrix.apps }}/" .helm-tmpl/Chart.yaml
        sed -i "s/^appVersion: .*/appVersion: ${{ needs.CI.outputs.tags }}/" .helm-tmpl/Chart.yaml

        echo "Deploying ${{ matrix.apps }} with image tag ${{ inputs.tags }}"

        helm upgrade --install --atomic \
          --create-namespace \
          --namespace ${{ matrix.apps }} \
          --set image.repository=${{ secrets.DOCKER_USERNAME }}/${{ matrix.apps }} \
          --set image.tag=${{ inputs.tags }} \
          -f .helm-tmpl/values.yaml -f ${{ matrix.apps }}/.helm/values.yaml -f ${{ matrix.apps }}/.helm/sandbox/values.yaml \
          ${{ matrix.apps }} .helm-tmpl
