name: CI

on:
  workflow_call:
    inputs:
      build_args:
        type: string
        description: List of build args for Docker build
        default: ""
        required: false
      paths_modified:
        type: string
        description: List of modified apps
        default: '["${{ github.event.repository.name }}"]'
        required: false
      skip_cd:
        type: string
        description: Apps to skip continuous deployment
        default: gha-runner
        required: false
    outputs:
      tag:
        description: Docker image tag
        value: ${{ jobs.CI.outputs.tag }}
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
        
jobs:
  CI:
    runs-on: ubuntu-latest
    if: ${{ inputs.paths_modified != '[]' }}
    outputs:
      tag: ${{ steps.set_tag.outputs.tag }}
    strategy:
      matrix:
        apps: ${{ fromJson(inputs.paths_modified) }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Check Docker daemon
      run: docker info

    - name: Set Build Context
      id: set_build_context
      run: |        
        if [ "${{ inputs.paths_modified }}" = ${{ github.event.repository.name }} ]; then
          build_context=.
        else
          build_context=${{ matrix.apps }}
        fi

        echo "build_context=$build_context" >> $GITHUB_OUTPUT

    - name: Set Image Tag
      id: set_tag
      run: |
        
        # There are two types of apps. One which have VERSION defined in Dockerfile like custom build addons e.g. gha-runner
        # Another type is standard apps where we use git branch name or tag name as version
        
        VERSION=$(grep 'ENV VERSION=' "${{ steps.set_build_context.outputs.build_context }}/Dockerfile" | cut -d'=' -f2)

        if [ "${{ github.event_name }}" = "pull_request" ]; then
          sha_short=$(echo "${{ github.event.pull_request.head.sha }}" | head -c5)
          if [ -n "$VERSION" ]; then
            tag="$VERSION-$sha_short"
          else
            tag="${{ github.head_ref }}-$sha_short"
          fi
        else
          if [ -n "$VERSION" ]; then
            tag="$VERSION"
          else
            tag="${{ github.ref_name }}-$(echo "${{ github.sha }}" | head -c5)"
          fi
        fi

        if ${{ inputs.skip_cd }} != ${{ matrix.apps }}; then
          echo "tag=$tag" >> $GITHUB_OUTPUT
        fi

    - name: Container Build
      uses: docker/build-push-action@v6
      with:
        context: ${{ steps.set_build_context.outputs.build_context }}
        load: true
        tags: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.apps }}:${{ steps.set_tag.outputs.tag }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      if: >  
        !contains(github.event.pull_request.labels.*.name, 'ci-skippush')
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Container image
      uses: docker/build-push-action@v4
      if: >
        !contains(github.event.pull_request.labels.*.name, 'ci-skippush')
      with:
        context: ${{ steps.set_build_context.outputs.build_context }}
        platforms: linux/amd64
        push: true
        tags:  ${{ secrets.DOCKER_USERNAME }}/${{ matrix.apps }}:${{ steps.set_tag.outputs.tag }}

    - name: Image digest
      run: echo ${{ steps.build.outputs.digest }}
