name: CD

on:
  workflow_call:
    inputs:
      paths_modified:
        type: string
        description: List of modified apps
      tag:
        type: string
        description: Docker image tag
        required: true
    secrets:
      DOCKER_PASSWORD:
        required: true
        
jobs:
  CD:
    runs-on: self-hosted
    if: >
      !contains(github.event.pull_request.labels.*.name, 'ci-skippush')
    strategy:
      matrix:
        apps: ${{ fromJson(inputs.paths_modified) }}
    steps:
    - name: Git clone the repository
      uses: actions/checkout@v4

    - name: Set up Helm
      uses: azure/setup-helm@v4.3.1
      with:
        version: 'latest'

    - name: Set App Name
      id: set_app_name
      run: |
        set +x
        app_name=$(echo "${{ matrix.apps }}" | cut -f2 -d '/')
        echo "app_name=$app_name" >> $GITHUB_OUTPUT

    - name: Deploy
      run: |
        set +x

        sed -i "s/^name: .*/name: ${{ steps.set_app_name.outputs.app_name }}/" .helm-tmpl/Chart.yaml
        sed -i "s/^appVersion: .*/appVersion: ${{ inputs.tag }}/" .helm-tmpl/Chart.yaml

        helm upgrade --install --rollback-on-failure \
          --create-namespace \
          --namespace ${{ steps.set_app_name.outputs.app_name }} \
          --set image.repository=${{ vars.DOCKER_USERNAME }}/${{ steps.set_app_name.outputs.app_name }} \
          --set image.tag=${{ inputs.tag }} \
          -f .helm-tmpl/values.yaml -f ${{ matrix.apps }}/.helm/values.yaml -f ${{ matrix.apps }}/.helm/sandbox/values.yaml \
          ${{ steps.set_app_name.outputs.app_name }} .helm-tmpl
