name: CD

on:
  workflow_call:
    inputs:
      paths_modified:
        type: string
        description: List of modified apps
      tag:
        type: string
        description: Docker image tag
        required: true
    secrets:
      DOCKER_USERNAME:
        required: true
        
jobs:
  CD:
    runs-on: self-hosted
    if: >
      !contains(github.event.pull_request.labels.*.name, 'ci-skippush')
    strategy:
      matrix:
        apps: ${{ fromJson(inputs.paths_modified) }}
    steps:
    - name: Git clone the repository
      uses: actions/checkout@v6

    - name: Set up Helm
      uses: azure/setup-helm@v4.3.1
      with:
        version: 'latest'

    - name: Deploy
      run: |
        set +x

        sed -i "s/^name: .*/name: ${{ matrix.apps }}/" .helm-tmpl/Chart.yaml
        sed -i "s/^appVersion: .*/appVersion: ${{ inputs.tag }}/" .helm-tmpl/Chart.yaml

        helm upgrade --install --atomic \
          --create-namespace \
          --namespace ${{ matrix.apps }} \
          --set image.repository=${{ secrets.DOCKER_USERNAME }}/${{ matrix.apps }} \
          --set image.tag=${{ inputs.tag }} \
          -f .helm-tmpl/values.yaml -f ${{ matrix.apps }}/.helm/values.yaml -f ${{ matrix.apps }}/.helm/sandbox/values.yaml \
          ${{ matrix.apps }} .helm-tmpl
