name: CI

on:
  workflow_call:
    inputs:
      build_args:
        type: string
        description: List of build args for Docker build
        default: ""
        required: false
      monorepo:
        type: boolean
        description: Whether the repo is a monorepo
        default: false
        required: false
      paths_modified:
        type: string
        description: List of modified apps
        default: '["${{ github.event.repository.name }}"]'
        required: false
      tag_latest:
        type: boolean
        description: Whether to tag the image as latest for main branch
        default: false
        required: false
    outputs:
      tag:
        description: Docker image tag
        value: ${{ jobs.CI.outputs.tag }}
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
        
jobs:
  CI:
    runs-on: ubuntu-latest
    if: ${{ inputs.paths_modified != '[]' }}
    outputs:
      tag: ${{ steps.set_tag.outputs.tag }}
    strategy:
      matrix:
        apps: ${{ fromJson(inputs.paths_modified) }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Check Docker daemon
      run: docker info

    - name: Set Build Context
      id: set_build_context
      run: |        
        if [ "${{ inputs.monorepo }}" = "true" ]; then
          build_context=${{ matrix.apps }}
        else
          build_context=.
        fi

        echo "build_context=$build_context" >> $GITHUB_OUTPUT

    - name: Set Tag
      id: set_tag
      run: |        
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          tag=${{ github.head_ref }}-$(echo "${{ github.event.pull_request.head.sha }}" | head -c5)
        elif [ "${{ inputs.tag_latest }}" = "true" ]; then
          tag=latest
        else
          tag=${{ github.ref_name }}-$(echo "${{ github.sha }}" | head -c5)
        fi

        echo "tag=$tag" >> $GITHUB_OUTPUT

    - name: Container Build
      uses: docker/build-push-action@v6
      with:
        context: ${{ steps.set_build_context.outputs.build_context }}
        load: true
        tags: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.apps }}:${{ steps.set_tag.outputs.tag }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      if: >  
        !contains(github.event.pull_request.labels.*.name, 'ci-skippush')
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Container image
      uses: docker/build-push-action@v4
      if: >
        !contains(github.event.pull_request.labels.*.name, 'ci-skippush')
      with:
        context: ${{ steps.set_build_context.outputs.build_context }}
        platforms: linux/amd64
        push: true
        tags:  ${{ secrets.DOCKER_USERNAME }}/${{ matrix.apps }}:${{ steps.set_tag.outputs.tag }}

    - name: Image digest
      run: echo ${{ steps.build.outputs.digest }}
