name: INIT

on:
  workflow_call:
    inputs:
      paths_include:
        type: string
        description: List of folders to consider for modification
        required: false
    outputs:
      paths_modified:
        description: List of modified apps
        value: ${{ jobs.INIT.outputs.paths_modified }}

jobs:
  INIT:
    runs-on: ubuntu-latest
    outputs:
      paths_modified:  ${{ steps.paths_modified.outputs.paths_modified }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Paths Modified
      id: paths_modified
      run: |
        set +x
        paths_modified=$(git diff HEAD HEAD~ --name-only \
          | grep '/' \
          | sort -u \
          | jq -R . | jq -s .)
        echo $paths_modified

        echo "paths_modified<<EOF" >> $GITHUB_OUTPUT
        echo "$paths_modified" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
