name: INIT

on:
  workflow_call:
    secrets:
      inherit: true
    inputs:
      paths_ignore:
        type: string
        description: List of folders or files to ignore changes
        required: false
    outputs:
      paths_modified:
        description: List of modified apps
        value: ${{ jobs.INIT.outputs.paths_modified }}
    # secrets:
    #   # AWS_IAM_GITHUB_OIDC_ROLE_ARN:
    #   #   required: true
    #   inherit: true

jobs:
  INIT:
    runs-on: ubuntu-latest
    outputs:
      paths_modified:  ${{ steps.paths_modified.outputs.paths_modified }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: INIT - Get Folders Changed
      id: paths_modified
      run: |
        paths_modified=$(git diff HEAD HEAD~ --name-only \
          | grep '/' \
          | cut -d'/' -f1 \
          | grep -vE '${{ inputs.paths_ignore }}' \
          | sort -u \
          | jq -R . | jq -s .)
        echo $paths_modified

        echo "paths_modified<<EOF" >> $GITHUB_OUTPUT
        echo "$paths_modified" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: INIT - Set AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5.1.1
      with:
        role-to-assume: ${{ secrets.AWS_IAM_GITHUB_OIDC_ROLE_ARN }}
        role-session-name: GitHubActions
        aws-region: ${{ vars.AWS_REGION }}

      # Upload a file to AWS s3
    - name: INIT - List a S3 Bucket
      run: |
          aws s3 ls s3://acb-bucket-presigned/
